=== Tape Framework pre.alpha

STATUS: Pre-alpha, in design and prototyping phase. Feedback appreciated. This
is an early preview. You will have to use clojure.deps with git coordinates for
now.

Inspired by https://github.com/duct-framework[Duct Framework],
https://github.com/tape-framework[Tape Framework] tries to be a Frontend
Doppelgänger. Useful for folks wanting ready-made DI/IOC-glue for their new
Re-Frame + Reagent apps. It also gives slightly more infrastructure, so you
don't start at zero.

There is a small link:../docs/Tutorial.adoc[Tutorial] and
link:../docs/Internals.md[Internals] description. To see how code based on it
looks, check out the https://github.com/tape-framework/7guis[Tape 7GUis]
implementation. To generate an app, check out the
https://github.com/tape-framework/clj-template[Code Generator].

It does:

1. Organize the frontend app around an Integrant system.
2. Build that system out of a module system (`tape.module` ported to cljc from
   Duct Framework).
3. Explore an alternative interface to Re-Frame (`tape.mvc`) that fits with
   Integrant.
4. Use conventions to thin the code down and make obvious what's where and what
   gets handled by what.
5. Build a body of recipes for dev workflow, routing, forms, validation etc.
   (`tape.dev`, `tape.router`, `tape.tools`, `tape.toasts`).

Future plans:

1. Right now `tape.mvc` is mostly just a proxy to Re-Frame.
   The **longer term stake** here is for things from system map to be injected
   in handlers and views (via fn params metadata) and allow to **move away from
   globals** (event-queue, app-db & other fxs state: to live in the system map).
   Expect breaking changes for that to happen.
2. Extract the "current view" mechanism in a module.

Notes:

1. It's all optional, you can use just the pieces you want. Don't like
   `tape.mvc`? Use plain `ig/init-key`. Don't like a certain module? Leave it
   out / bring your own.
2. The default experience is "prefer easy". If you prefer simple, just don't use
   the parts that seem magic (like, say, modules discovery) and be a bit more
   verbose in configs.

Individual merits of some of the subprojects:

1. https://github.com/tape-framework/module[Tape Module] the module system
   ported from Duct, now available in ClojureScript - with a certain level of
   generality.
2. https://github.com/tape-framework/refmap[Tape RefMap] like Integrant's RefSet
   but brings the key in the output and returns a hash-map.
3. https://github.com/tape-framework/tools[Tape Tools] lens and form bits are
   useful outside Tape too.
4. https://github.com/tape-framework/dev[Tape Dev] can be used standalone.
